language: c
dist: bionic
sudo: true
addons:
  apt:
    packages:
    - ocaml-nox
    - libogg-dev
    - libflac-dev

before_install:
  - git clone https://github.com/savonet/ocaml-ogg.git
  - cd ocaml-ogg && git submodule init && git submodule update && ./bootstrap && ./configure && make && sudo make install

script:
  - ./bootstrap
  - ./configure
  - make
  - make -C examples
